### ISSUE TITLE
Max line width break formatting

### ISSUE THREAD

**Issue by lpgauth** [WhatsApp/erlfmt#118]
Hi, I'm curious about the formatting choice when a line is over the max width. Why not try to minimize the number of lines instead of going full vertical?

Currently this line:
```erlang
scenario(dial_phone_number(),  ring(), hello(mike),hello(joe), hello(robert),   system_working(), seems_to_be())
```
becomes:
```erlang
scenario(
    dial_phone_number(),
    ring(),
    hello(mike),
    hello(joe),
    hello(robert),
    system_working(),
    seems_to_be()
)
```
Why not:
```erlang
scenario(dial_phone_number(), ring(), hello(mike), hello(joe), hello(robert), system_working(), 
    seems_to_be())
```

I find going full vertical very "verbose", it takes a lot of screen real-estate without much added value. The only advantage I can see is that it might make some people write shorter functions to not end up with that formatting 🤷 

BTW, thanks for taking the time to write this formatter. I understand it's a non trivial thing to build and it's impossible to make everyone happy.

**Comment by lpgauth** [comment]
So after looking at the code, why not use flex breaks instead of strict breaks?

```erlang
 break(String) when is_binary(String) ->
-    #doc_break{break = String, flex_or_strict = strict}.
+    #doc_break{break = String, flex_or_strict = flex}.
```

**Comment by michalmuskala** [comment]
Thank you for trying erlfmt out and giving your feedback!

The primary advantage of this choice is to avoid important information drifting to the right. In my experience when scanning code we tend to stick to the left margin, having completely new syntactical elements far to the right makes the code harder to comprehend.

But ultimately the main factors for the decision were "prior art":
* The pattern of having one element per line for multiline expressions was most common in Erlang code I explored before starting the formatter. It was either the particular style that was chosen or:

      scenario(dial_phone_number(),
               ring(),
               hello(mike),
               hello(joe),
               hello(robert),
               system_working(),
               seems_to_be())

  This "hugging" style has a problem of "floating" elements - renaming one thing (like the function name) can lead to unnecessary extra re-indents and that's why it was rejected.
* This is in line with styles of other formatters that I'm familiar with (for example `mix format`, `prettier`, and `rustfmt`)

**Comment by lpgauth** [comment]
Cool, thanks for the quick reply. I checked with the team and it seems everyone prefers your formatting style so I guess I'll have to live with it :D

**Comment by awalterschulze** [comment]
Thank you so much for checking with your team, this is very valuable to know.
And thank you for being so accommodating.
