### ISSUE TITLE
Add --check command

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#14]
See https://prettier.io/docs/en/cli.html#--check for an example how it should work

**Comment by awalterschulze** [comment]
The printout should be something like this.

```
Checking formatting...
src/fileA.erl
src/fileB.erl
Code style issues found in the above file(s). Forgot to run erlfmt?
```

If some files aren't formatted erlfmt should exit with exit code 1

**Comment by awalterschulze** [comment]
The problem is not when comparing with a set of formatted files, this can be done by rereading the original file and comparing it against the output before writing to the file.  So in this case there is no need for the temporary folder.

The problem is when we get input from standard_in to format.  Then we cannot reread the input using the filename.  So in this case it might be useful to write to a temporary folder.  We would need this folder to be created in a os independent way, using some function that understands how to create a temporary folder on at least windows, mac and linux.  I am quite new to erlang, so not too familiar with the standard library, is such a function available?

Either way I will start to add support for non standard input.  If we figure out how to do standard_input we can add that later.

Btw @elbrujohalcon do you have a standard input use case for `--check` ?

**Comment by elbrujohalcon** [comment]
`rebar3 format` doesn't accept `stdin` as input, no.
