### ISSUE TITLE
Keep track of right hand side when aligning code

### ISSUE THREAD

**Issue by edvreu** [WhatsApp/erlfmt#144]
erlfmt moves code, that is on the right side of an equals sign, to the left side.  That is not beautiful code in my eyes. A simple example:
```erlang
example_function() ->	
    Variable = my_function(Argument1, Argument2, Argument3, Argument4, Argument5, Argument6, Argument7, Argument8).
```
Looks like this after running erlfmt:
```erlang
example_function() ->
    Variable = my_function(
        Argument1,
        Argument2,
        Argument3,
        Argument4,
        Argument5,
        Argument6,
        Argument7,
        Argument8
    ).
```
However, the arguments belong to the right side and should be aligned with that like this:
```erlang
example_function() ->
    Variable = my_function(
                   Argument1,
                   Argument2,
                   Argument3,
                   Argument4,
                   Argument5,
                   Argument6,
                   Argument7,
                   Argument8
    ).
```
Or a new line should be inserted after the equal sign:
```erlang
example_function() ->
    Variable = 
        my_function(
            Argument1,
            Argument2,
            Argument3,
            Argument4,
            Argument5,
            Argument6,
            Argument7,
            Argument8
    ).
```

**Comment by awalterschulze** [comment]
Hi @edvreu thank you for opening the discussion.
This is a very interesting point.
I never thought of expressions on the next line still being "connected" to the equal sign, but now that you mention it, it is forever burned into my brain :D

`erlfmt` avoids floating alignment that aligns different lines with each other as much as possible, because given the following example:
```erlang
example_function() ->
    Variable = my_function(
                   Argument1,
                   Argument2,
                   Argument3,
                   Argument4,
                   Argument5,
                   Argument6,
                   Argument7,
                   Argument8
    ).
```
If we change `Variable` to `Var` the diff would result in changing a whole bunch of lines, instead of a possible single line.

On the other hand, if I recall correctly, something very close to your other example was actually implemented in `erlfmt` until very recently:
```erlang
example_function() ->
    Variable = 
        my_function(
            Argument1,
            Argument2,
            Argument3,
            Argument4,
            Argument5,
            Argument6,
            Argument7,
            Argument8
        ).
```
But if `Variable` suddenly had a very long name:
```erlang
example_function() ->
    MyResultFromMyFunction = 
        my_function(
            Argument1,
            Argument2,
            Argument3,
            Argument4,
            Argument5,
            Argument6,
            Argument7,
            Argument8
        ).
```
Then the arguments would be on the left side again.
Do you have any more ideas or thoughts about this?

**Comment by edvreu** [comment]
The last example with the long variable name is correct indented to me, since you break the line after the equals sign. When you read this code you immediately see that the variable equals to the return value, from the function with all the arguments.

The problem only occurs when you leave something on the right side of the equals sign. Then it is harder to see what the arguments belong to.

A quick example with an extra function call, that gets hard to read:
```erlang
example_function() ->
    Variable = my_function(
        my_second_function(
            Argument1,
            Argument2,
            Argument3,
            Argument4,
            Argument5,
            Argument6,
            Argument7,
            Argument8
        )
    ).

```

**Comment by michalmuskala** [comment]
I verified and we do support this style. There are two stable formats for the following expression (stable meaning erlfmt won't change them):

```erl
Variable = 
    my_function(
        Argument1,
        Argument2,
        Argument3,
        Argument4,
    ).
```
and
```erl
Variable = my_function(
    Argument1,
    Argument2,
    Argument3,
    Argument4
).
```

This is controlled by whether there was a newline between `=` and the call.

What @awalterschulze referred to was us removing support for such distinction in lists/tuples and other "simple" containers, for example:
```erl
Variable = [
    Value1,
    Value2,
    Value3,
    Value4
].
```
is the only stable form to write this (with a list over multiple lines). If there's a new line between `=` and `[` it will be removed. The reasoning behind this behaving different is that it makes sense for the function name to appear on its own line (since it carries important semantic information); it makes less sense for `[` to appear on a line of its own - there's very little information contained in that line, it might as well be right after the `=`.

**Comment by edvreu** [comment]
The first part does not work for me, erlfmt always puts the function call on the same line as the equals sign, no matter how the code looked before.
Could it be made an option to force this behavior (in case you don't want to preformat a lot of old code)?

To me the way you format the list in this case is also wrong, since it also belongs to the right side of the equals sign.

I also noticed that you treat list comprehensions differently, they get a new line (and are nicely formatted thanks to that):
```erlang
Variable =
    [
        my_function(Argument1, Argument2)
        || {Argument1, Argument2} <- List, Argument =/= invalid_value
    ].
```

**Comment by michalmuskala** [comment]
There were some changes around this that we did quite recently. Perhaps you're not on the latest version? What do you get from `erlfmt --version` or `rebar3 fmt --version?

**Comment by edvreu** [comment]
I built the escript from the latest master today, however, it is on my work computer so I can't check the output of the command now.
No, I'm afraid it does not depend on what is to the left of the equals sign, it is about what is to the right. Let me try to make some examples to help you understand my view.
1. This is fine, it is easy to read both expressions in this case:
```erlang
SomeSuperLongVariableNameOrPerhapsEvenAComplexAndNestedPattern =
    SomeOtherSuperLongVariableNameOrPerhapsEvenAComplexAndNestedPattern
```
2. Here is where I get a problem, I loose the connection between the parts on the right side:
```erlang
SomeSuperLongVariableNameOrPerhapsEvenAComplexAndNestedPattern = StartOfComplexExpression2
    RestOfComplexExpression2
```
3. Another example, would you ever consider formatting a case statement like this?
```erlang
Variable = case Something of
    case1 ->
        ...
    case2 ->
        ...
end.
```
This is how I feel you do right now, you leave a bit of an expression hanging on the right, while the rest of the code has moved to the left and lost its connection with it.

**Comment by michalmuskala** [comment]
I believe we fixed this mostly in current `master`. Newline after `=` is respected and preserved in function calls, which was the original issue raised here. In other words, there are 2 stable formats erlfmt won't change:
```erlang
example_function() ->
    Variable = my_function(
        Argument1,
        Argument2,
        Argument3,
        Argument4,
        Argument5,
        Argument6,
        Argument7,
        Argument8
    ).
```
and
```erlang
example_function() ->
    Variable = 
        my_function(
            Argument1,
            Argument2,
            Argument3,
            Argument4,
            Argument5,
            Argument6,
            Argument7,
            Argument8
    ).
```

I'm going to close this.
