### ISSUE TITLE
Lists: Minimizing diff in multiline collection

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#150]
Currently when a collection is to be formatted in multiline fashion (either due to the line length or user intention) it ends up like this:
```
[
    x,
    y
]
```
This looks good visually but there is a problem regarding the diff size when adding a new element into the list:
```
[
    x,
    y,
    z
]
```
The diff shows changes in two lines instead of one.

Did you try to adress this issue somehow? I noticed that you did consider the "minimal diff" argument elsewhere, e.g. https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionComments.md.

In our codebase we tackle this problem with the leading comma trick:
```
[ x
, y
]
```
Well, I admit it looks visually quite strange at first but there was no other solution we could think of :-)

**Comment by awalterschulze** [comment]
Thank you @david-kubecka for bringing this up.
I think this points to a missing formatting decision document, where we can have a discussion and finalize a decision.
I suspect you are not the first or last to ask this question :)

**Comment by elbrujohalcon** [comment]
The good ol' ROK-style formatting... :trollface:

**Comment by michalmuskala** [comment]
The proper solution would be to add trailing comments to the language.

Comma-first style while existing in Erlang, is generally not super popular and completely foreign in mainstream programming languages.

**Comment by awalterschulze** [comment]
We recognize that this is a very divisive issue.
We decided to do an analysis https://github.com/WhatsApp/erlfmt/pull/187
Let me know what you think.

**Comment by paulo-ferraz-oliveira** [comment]
Adding a new data point (to be clear, I'm **not against** the comma-as-suffix decision`[1]`): https://gist.github.com/isaacs/357981.

I just want to add to @michalmuskal's "completely foreign in mainstream programming languages" (JavaScript is, as of now, GitHub's most popular programming language).

Of course, in Erlang, this wouldn't compile:
```erlang
// error in standard style
A = "ape",
B = "bat",
C = "cat",
D = "dog"
E = "elf",
F = "fly",
G = "gnu",
H = "hat",
I = "ibu"
```
but this makes it "more visible":
```erlang
// error in comma-first style
  A = "ape"
, B = "bat"
, C = "cat"
, D = "dog"
E "elf"
, F = "fly"
, G = "gnu"
, H = "hat"
, I = "ibu".
```

`[1]` I actually prefer it.

**Comment by paulo-ferraz-oliveira** [comment]
In PHP, [Multi-line declaration/condition/concatenation](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#multi-line-declarationconditionconcatenation) is inconsistent with [Multi-line arrays](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#multi-line-declarationconditionconcatenation), for example - and they aim at a standard 😄.

All in all:
1. if there's a clear rule that's adopted consistently, that's a good thing,
2. if that rule implies little change to existing code, that's a good thing (which is why you're scope analysis is important).

**Comment by awalterschulze** [comment]
Yes there are many good reasons for comma first style and in fact I am a fan of it ... don't tell anyone ;)
But I think the conformity is more valuable than my own preferences, because then I can work with less friction with more people.

**Comment by elbrujohalcon** [comment]
@awalterschulze what about the conformity around those who _really want_ to format their code? Like you, and me, and @robertoaloi... :trollface:

**Comment by david-kubecka** [comment]
> @awalterschulze what about the conformity around those who _really want_ to format their code? Like you, and me, and @robertoaloi... :trollface:

This is actuall yvery good point. In my current company there were efforts to introduce automatic formatting to an unmaned language. The formatter produced quite ugly formatting according to most people but the consistency and readability (and other features such as minimizing diffs) was rated much higher. I'm afraid that if your goal is to create "the" Erlang formatter you will have to make some unpopular decisions anyway. If it's for a good thing...

**Comment by awalterschulze** [comment]
@david-kubecka interesting data point.
I think this type of decision can make sense, given a new language and some other circumstances.

Unfortunately since we are retro fitting a formatter onto an already existing community, this will be a tougher sell, given the data #187

**Comment by awalterschulze** [comment]
@elbrujohalcon we are only 3 people (sorry 4). The data suggests, we are out numbered :(

**Comment by elbrujohalcon** [comment]
Just for the sake of argument…

I know more than 4 people that prefer comma first, for instance… Richard O'Keefe, @robertoaloi, @jfacorro (and all of his colleagues from @klarna), @igaray, @harenson (and many of his colleagues from @2600hz), @paulo-ferraz-oliveira, @awalterschulze …

And I know some people who, even when they like in comma-suffix style, they can appreciate the benefits of comma-first, like @amilkr, @alemata, @pbrudnick, @diegomanuel (and some of his colleagues at @fiqus), @michalmuskala (I believe), and others…

Yes, this is a topic that I have discussed **a lot** over the last 10 years. 🤓 

We're outnumbered… maybe… but so was every single revolutionary genius in history, right?

**Comment by elbrujohalcon** [comment]
Just to be clear: I'm not advocating for `erlfmt` to implement comma-first… I don't really care, I'll eventually implement `rok_formatter` for `rebar3 format` and code happily everafter 🌈 🦄

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira 

I don't prefer it, actually, but, as you stated, can appreciate its benefits. I just do it if _I have to_ (for consistency or because it's enforced). I prefer "operators as prefix" though, but that's not because of "diff.", that's because it's easier for me to read. (and that's a whole other discussion, I guess)

**Comment by awalterschulze** [comment]
So I think after reading through all this again, it seems we somewhat agree, that the current way of formatting lists is at least okay for erlfmt.
It is not an easy decision and we are upsetting some people, like myself, but the conformity is not too bad in this case.
We also do not minimize the diff to the absolute minimum, but we get very close to the minimum 2 lines instead of 1.
I hope we can consider this case closed, but let me know if I misinterpreted.
