### ISSUE TITLE
Strange formatting of long tuples

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#151]
```
{aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccccc, ddddddddddddddddddddddddddddddddd}
```
gets formatted into
```
{aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
        ccccccccccccccccccccccccccccccccc, ddddddddddddddddddddddddddddddddd}
```
Is this really intended? I would expect that it behaves similarly as if the elements were put into a list instead which ends up like this:
```
[
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
        ccccccccccccccccccccccccccccccccc,
        ddddddddddddddddddddddddddddddddd
]
```

**Comment by awalterschulze** [comment]
Yes tuples are formatted to fit and not like lists.
Reason being, in a list every element has the same importance.
On the other hand erlang tuples are usually tagged, which means the first element is typically more important, so:
```erlang
{ok, verylongvalue}
```
would be better formatted to
```erlang
{ok,
    verylongvalue}
```
rather than:
```erlang
{
    ok,
    verlongvalue
}
```
At least that is our reasoning.
What do you think?

**Comment by michalmuskala** [comment]
It's important to note that you can explicitly format the tuple like a list by adding a newline between `{` and the first element. So both formats are supported in tuples, it's just about the default.

**Comment by david-kubecka** [comment]
I understand the reasoning and it makes perfect sense.
