### ISSUE TITLE
Wrong placement of comment

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#160]
Input:
```
f(1,
    2). % comment
```
Result:
```
f(
    1,
    % comment
    2
).
```
This is IMO wrong since the comment clearly belongs to the whole `f(...)` expression so the result should rather be:
```
% comment
f(
    1,
    2
).
```

Or, preferably, keep the comment inlined:
```
f(
    1,
    2
). % comment
```

**Comment by michalmuskala** [comment]
This is very similar to what's happening in https://github.com/WhatsApp/erlfmt/issues/134 and https://github.com/WhatsApp/erlfmt/issues/165 that comes from our very simple rules on handling trailing comments. Since there's more discussion around this happening in https://github.com/WhatsApp/erlfmt/issues/134, I'm going to close this issue in favour of the discussion happening there.
