### ISSUE TITLE
CLI: Do not write file if format fails

### ISSUE THREAD

**Issue by ebengt** [WhatsApp/erlfmt#162]
When erlfmt fails to format a file it should not be written. Add new flag, -f, if this is really needed behaviour.
I can write a patch if you are interested (to stop file being written after failure. Not for -f)

With erlfmt version 0.7.0

$ erlfmt -w src/erlfmt_parse.yrl
src/erlfmt_parse.yrl:19:1: syntax error before: node
...
src/erlfmt_parse.yrl:631:8: syntax error before: code

$ git status
	modified:   src/erlfmt_parse.yrl

**Comment by michalmuskala** [comment]
This is on purpose. Erlfmt will format all the forms in the file that can be properly parsed, those that can't are copied without change. 

This is needed because of various complex macros you might have that erlfmt does not handle. Instead of skipping the whole file when just one function is problematic, erlfmt skips only this one function, but formats everything else just fine

**Comment by awalterschulze** [comment]
@ebengt I notice you are formatting a `.yrl` file, we do not support this yet https://github.com/WhatsApp/erlfmt/issues/41

Despite that I agree with @michalmuskala .  This is intended behaviour.
Is there a specific use case you think would make it very important to support this flag?
  - Is it impossible to exclude `.yrl` files in your file set?
  - Was the formatting of the `.yrl` unacceptable (we deleted some code or comments)?
  - Something else we haven't thought of?

Or do you think we can close this issue?

**Comment by ebengt** [comment]
Yes, I will close the issue. I thought that writing a file that did not format correctly was sufficiently ''strange'' to merit a flag, but when the problematic part is kept unchanged it does not need a flag.
