### ISSUE TITLE
Case: Consider different formatting of `case` statement

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#164]
This is kind of obvious because this formatting was surely a deliberate decision:
```
A = case X of true -> f(); _ -> g() end.

A =
    case X of
        true -> f();
        _ -> g()
    end.
```
I would like to still open up a discussion (perhaps it's already discussed somewhere else) as to why you decided against this option:
```
A = case X of
    true -> f();
    _ -> g()
end.
```
Especially when there is very similar formatting in the case of function calls:
```
A = f(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccccccccccccc).

A = f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccccccccccccccccccc
).
```

Also some other language constructs (notably `try ... catch`) should ideally follow the same formatting logic.

**Comment by michalmuskala** [comment]
The immediate reasoning for why this particular decision was made, is because that's what Elixir formatter does (and it was used frequently as a reference point).

The more principled reason is that I believe the formatter should avoid information drifting to the right. In particular, when scanning text, I do not want any important information to be "hidden" deep into expressions on the right.

The formatting of functions after `=` is one of the compromises we made early in the project and should not be regarded as a rule. Perhaps it would be right to remove even that now that we had more time to evaluate the project.

**Comment by paulo-ferraz-oliveira** [comment]
I'm used to writing (somewhat) like either the initial comment
```erlang
A = case X of
    true ->
        f();
    _ ->
        g()
end.
```
or (in special cases)
```erlang
IfSomethingWouldShiftTooMuch
    = case X of
          true ->
              f();
          _ ->
              g()
      end.
```

**Comment by paulo-ferraz-oliveira** [comment]
In the case of a run I did over some files
```erlang
    case whereis(ServerAndTable) =/= undefined
         orelse counter_sup:start_child([ServerAndTable, Name])
```
was changed to
```erlang
    case
        whereis(ServerAndTable) =/= undefined orelse
            counter_sup:start_child([ServerAndTable, Name])
```
(as stated in other issues, I prefer my "operators" on the left side 😄)

**Comment by awalterschulze** [comment]
I think the original issue was answered.  Happy to answer the other concerns in other issues, but let us try to avoid conflating multiple issues together as it makes it very hard to answer and close these issues.
