### ISSUE TITLE
Allowing `insert-pragma` and `require-pragma` together

### ISSUE THREAD

**Issue by filmor** [WhatsApp/erlfmt#252]
To gradually roll out formatting on our repo I'd like to have a "mixed" mode operation for the require and insert flags. Namely, I want 

* `rebar3 fmt -w some/file.erl` to insert the pragma, while 
* `rebar3 fmt -w` should only touch files that already have a pragma.

Would a change like this be "mergeable"? :)

**Comment by awalterschulze** [comment]
Really interesting use case.  Hmmm. 
I actually do not know how to do this in a reasonable way, without introducing another option.
Maybe you have ideas?

## Cases to think about:

1. Once the whole codebase is opted in, it would make sense to stop requiring a pragma and inserting it
2. Users that are already using erlfmt and do not expect it to insert pragma (probably less important as we have not officially released 1.0.0 yet and we still have small room to adjust behaviour)

## Code pointer:

Checking for a single file can be done somewhere close to here
https://github.com/WhatsApp/erlfmt/blob/master/src/erlfmt_cli.erl#L68

**Comment by awalterschulze** [comment]
I was thinking more about this.
Possibly we should allow having both `--require-pragma` and `--insert-pragma`, but where `--insert-pragma` simply overrides `--require-pragma`

Then users could have the following rebar.config profile
```
{erlfmt, [
    write,
    require_pragma,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
Then to insert the `@format` comment, users do not have to pass the flag `-w`, but still need to pass the flag `--insert-pragma`
```
$ rebar3 fmt --insert-pragma some/file.erl
```
And to format all files with the `--require-pragma` would be:
```
$ rebar3 fmt 
```

If we then also allow a shortcut for `--insert-pragma` to be `-i`, then inserting would become
```
$ rebar3 fmt -i some/file.erl
```
which is just as short as writing the original suggestion by @filmor and doesn't cause any confusion.

We could have to the same overriding, where `check` overrides `write`, so that CI can then simply call:
```
$ rebar3 fmt --check
```

What do others think?

**Comment by michalmuskala** [comment]
I think it might already be working like this - options from CLI should be overriding options given in the config file. I haven't verified, though

**Comment by awalterschulze** [comment]
This is exactly what I just found :)

**Comment by awalterschulze** [comment]
So was about to rewrite my comment.
I think all we need to do is add shortcuts for `--insert-pragma` and `--require-pragma` as `-i` and `-r` respectively.
Then if you setup your rebar.config as
```
{erlfmt, [
    write,
    require_pragma,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
The users can run the following to insert-pragma into a single file:
```
$ rebar3 fmt -i some/file.erl
```
And run the following to format all files:
```
$ rebar3 fmt
```
And CI can run
```
$ rebar3 fmt --check
```

I know this is not exactly what @filmor requested, but as I have stated [before](https://github.com/WhatsApp/erlfmt/issues/252#issuecomment-783281424), I think it isn't as simple as allowing both.

I hope that this shorthand will provide enough ease of use without any of the complications.

**Comment by filmor** [comment]
This doesn't work. The `require_pragma` from `rebar.config` is still taken into account, so the file will not be changed. That's exactly the issue I'm facing right now :)

**Comment by awalterschulze** [comment]
Let me double check this.  Thank you for letting me know.

**Comment by awalterschulze** [comment]
I tried it again with the following in my `rebar.config` file

```
{erlfmt, [
    write,
    require_pragma,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```

I then ran
`$ rebar3 fmt --insert-pragma ./src/example.erl `
and it formatted and inserted the pragma

If you can give me a repo to look at I can try that, but otherwise I am struggling to reproduce the issue and I believe the merged commit is as close we are going to come to making this as smooth as possible.
