### ISSUE TITLE
Syntax error when parsing macros

### ISSUE THREAD

**Issue by dziaineka** [WhatsApp/erlfmt#314]
Hello! I've made simple example:

```erlang
-module(example_module).

-export([example_function/2]).

-define(CATCH_SPECIAL_ERROR(HandleFunction),
        error:(E = some_special_error) -> HandleFunction(E)).

example_function(Data, Function) ->
    try Function(Data)
    catch
        ?CATCH_SPECIAL_ERROR(
            fun(SpecialError) ->
                some_action(),
                {error, SpecialError}
            end
        );

        Error:_Reason:_Stacktrace ->
            {error, Error}
    end.

some_action() ->
    some_action.

```

Where erlfmt shows me errors:

```
example_module.erl:6:14: syntax error before: ':'
example_module.erl:12:13: syntax error before: 'fun'
```

But the code seems to be valid.

Thank you!

**Comment by michalmuskala** [comment]
I'm sorry for a late reply.

Unfortunately supporting this sort of syntax with the current parser is extremely challenging - I've tried couple times to make this work, but I was not able to - primarily because it's "hiding" the structure of the program with the standalone `->` token unrelated to surrounding code.

As such I'm going to close this issue.
